#  Copyright 1999-2019 Seata.io Group.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or ag`reed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
server:
  port: 7091
  ssl:
    # 开启证书
    enabled: false
    # 证书位置
    key-store: classpath:scg-keystore.p12
    # 证书别名
    key-alias: ${spring.application.name}
    # 秘钥类型
    key-store-type: PKCS12
    # 证书密码
    key-store-password: laokou
  http2:
    enabled: true
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: @JASYPT-ENCRYPTOR-PASSWORD@

spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @PROFILE-ACTIVE@

logging:
  config: classpath:logback-spring.xml
  file:
    path: ./logs/seata
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: @SEATA-USERNAME@
    password: @SEATA-PASSWORD@

seata:
  config:
    type: nacos
    nacos:
      server-addr: @NACOS-CONFIG-ADDRESS@
      namespace: @NACOS-NAMESPACE@
      group: @SEATA-GROUP@
      username: @NACOS-USERNAME@
      password: @NACOS-PASSWORD@
  registry:
    type: nacos
    nacos:
      server-addr: @NACOS-DISCOVERY-ADDRESS@
      group: @SEATA-GROUP@
      namespace: @NACOS-NAMESPACE@
      username: @NACOS-USERNAME@
      password: @NACOS-PASSWORD@
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login